version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maple-user-account
    ports:
      - '5404:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local